### PR TITLE
tervezett 7. módosítás

### PR DESCRIPTION
**Pull request by orbanviktor**
Dear maintainer(s), I would be willing to set up continuous integration for this project, if I would have the rights. Please grant me (and my organization) write access to the master branch, thank you.

### CODE REVIEW

**Comment by TamasSzerb** [comment]
Dear @orbanviktor, according to the parliament's decision I'm afraid your pull request cannot be delivered at this moment.

**Comment by petergerner** [comment]
Ez a Github, nem a Parlament. :)
Itt csak követni tudjuk, hogy mi történik az Alaptörvénnyel, változtatni rajta máshol kell.

**Comment by grinapo** [comment]
"the Parliament has rejected the pull request and closed the issue" ;-)

**Comment by petergerner** [comment]
#11 szerint újranyitva

**Pull request merged**
